// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UavStateMessage.proto

package com.ruoyi.web.pb;

public final class UavStateMessageOuterClass {
  private UavStateMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruoyi_web_pb_SearchInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruoyi_web_pb_SearchInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruoyi_web_pb_UavStateMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruoyi_web_pb_UavStateMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruoyi_web_pb_PosInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruoyi_web_pb_PosInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ruoyi_web_pb_Hobby_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ruoyi_web_pb_Hobby_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025UavStateMessage.proto\022\020com.ruoyi.web.p" +
      "b\"\242\001\n\nSearchInfo\022\013\n\003num\030\001 \001(\005\022\014\n\004uuid\030\002 " +
      "\001(\t\022\"\n\003sex\030\003 \001(\0162\025.com.ruoyi.web.pb.Sex\022" +
      "+\n\010baseInfo\030\004 \001(\0132\031.com.ruoyi.web.pb.Pos" +
      "Info\022(\n\007hobbies\030\005 \003(\0132\027.com.ruoyi.web.pb" +
      ".Hobby\"\202\004\n\017UavStateMessage\022\013\n\003lng\030\001 \001(\001\022" +
      "\013\n\003lat\030\002 \001(\001\022\020\n\010altitude\030\003 \001(\002\022\022\n\nultras" +
      "onic\030\004 \001(\002\022\r\n\005pitch\030\005 \001(\002\022\014\n\004roll\030\006 \001(\002\022" +
      "\013\n\003yaw\030\007 \001(\002\022\020\n\010airspeed\030\010 \001(\002\022\020\n\010veloci" +
      "ty\030\t \001(\002\022\021\n\ttimestamp\030\n \001(\004\022\017\n\007ptpitch\030\013" +
      " \001(\002\022\016\n\006ptroll\030\014 \001(\002\022\r\n\005ptyaw\030\r \001(\002\022\022\n\nz" +
      "oomfactor\030\016 \001(\002\022\r\n\005boxSn\030\017 \001(\t\022\024\n\014batter" +
      "yPower\030\020 \001(\t\022\026\n\016satelliteCount\030\021 \001(\r\022\016\n\006" +
      "taskId\030\022 \001(\004\022\016\n\006rtkLng\030\023 \001(\001\022\016\n\006rtkLat\030\024" +
      " \001(\001\022\017\n\007rtkHFSL\030\025 \001(\002\022\027\n\017rtkPositionInfo" +
      "\030\026 \001(\r\022\023\n\013airFlyTimes\030\027 \001(\r\022\026\n\016airFlyDis" +
      "tance\030\030 \001(\002\022\r\n\005uavSn\030\031 \001(\t\022\020\n\010uavModel\030\032" +
      " \001(\t\022\021\n\thomeRange\030\033 \001(\002\022\022\n\nflightMode\030\034 " +
      "\001(\r\"(\n\007PosInfo\022\017\n\007address\030\001 \001(\t\022\014\n\004desc\030" +
      "\002 \001(\t\"#\n\005Hobby\022\014\n\004name\030\001 \001(\t\022\014\n\004desc\030\002 \001" +
      "(\t*\030\n\003Sex\022\007\n\003BOY\020\000\022\010\n\004GIRL\020\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ruoyi_web_pb_SearchInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ruoyi_web_pb_SearchInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruoyi_web_pb_SearchInfo_descriptor,
        new String[] { "Num", "Uuid", "Sex", "BaseInfo", "Hobbies", });
    internal_static_com_ruoyi_web_pb_UavStateMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ruoyi_web_pb_UavStateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruoyi_web_pb_UavStateMessage_descriptor,
        new String[] { "Lng", "Lat", "Altitude", "Ultrasonic", "Pitch", "Roll", "Yaw", "Airspeed", "Velocity", "Timestamp", "Ptpitch", "Ptroll", "Ptyaw", "Zoomfactor", "BoxSn", "BatteryPower", "SatelliteCount", "TaskId", "RtkLng", "RtkLat", "RtkHFSL", "RtkPositionInfo", "AirFlyTimes", "AirFlyDistance", "UavSn", "UavModel", "HomeRange", "FlightMode", });
    internal_static_com_ruoyi_web_pb_PosInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ruoyi_web_pb_PosInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruoyi_web_pb_PosInfo_descriptor,
        new String[] { "Address", "Desc", });
    internal_static_com_ruoyi_web_pb_Hobby_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ruoyi_web_pb_Hobby_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ruoyi_web_pb_Hobby_descriptor,
        new String[] { "Name", "Desc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
