// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UavStateMessage.proto

package com.ruoyi.web.pb;

public interface UavStateMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ruoyi.web.pb.UavStateMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *经度
   * </pre>
   *
   * <code>double lng = 1;</code>
   */
  double getLng();

  /**
   * <pre>
   *纬度
   * </pre>
   *
   * <code>double lat = 2;</code>
   */
  double getLat();

  /**
   * <pre>
   *海拔高度(椭球高)(单位:米)
   * </pre>
   *
   * <code>float altitude = 3;</code>
   */
  float getAltitude();

  /**
   * <pre>
   *相对高度(单位:米)
   * </pre>
   *
   * <code>float ultrasonic = 4;</code>
   */
  float getUltrasonic();

  /**
   * <pre>
   *俯仰角
   * </pre>
   *
   * <code>float pitch = 5;</code>
   */
  float getPitch();

  /**
   * <pre>
   *横滚角
   * </pre>
   *
   * <code>float roll = 6;</code>
   */
  float getRoll();

  /**
   * <pre>
   *偏航角
   * </pre>
   *
   * <code>float yaw = 7;</code>
   */
  float getYaw();

  /**
   * <pre>
   *空速(单位:米/秒)
   * </pre>
   *
   * <code>float airspeed = 8;</code>
   */
  float getAirspeed();

  /**
   * <pre>
   *地速(单位:米/秒)
   * </pre>
   *
   * <code>float velocity = 9;</code>
   */
  float getVelocity();

  /**
   * <pre>
   *时间戳
   * </pre>
   *
   * <code>uint64 timestamp = 10;</code>
   */
  long getTimestamp();

  /**
   * <pre>
   *载荷俯仰角
   * </pre>
   *
   * <code>float ptpitch = 11;</code>
   */
  float getPtpitch();

  /**
   * <pre>
   *载荷横滚角
   * </pre>
   *
   * <code>float ptroll = 12;</code>
   */
  float getPtroll();

  /**
   * <pre>
   *载荷航向角
   * </pre>
   *
   * <code>float ptyaw = 13;</code>
   */
  float getPtyaw();

  /**
   * <pre>
   *载荷当前倍数
   * </pre>
   *
   * <code>float zoomfactor = 14;</code>
   */
  float getZoomfactor();

  /**
   * <pre>
   *云盒子编号
   * </pre>
   *
   * <code>string boxSn = 15;</code>
   */
  String getBoxSn();
  /**
   * <pre>
   *云盒子编号
   * </pre>
   *
   * <code>string boxSn = 15;</code>
   */
  com.google.protobuf.ByteString
      getBoxSnBytes();

  /**
   * <pre>
   *电池电量,多个电池以下划线分割,如：80_60
   * </pre>
   *
   * <code>string batteryPower = 16;</code>
   */
  String getBatteryPower();
  /**
   * <pre>
   *电池电量,多个电池以下划线分割,如：80_60
   * </pre>
   *
   * <code>string batteryPower = 16;</code>
   */
  com.google.protobuf.ByteString
      getBatteryPowerBytes();

  /**
   * <pre>
   *卫星计数
   * </pre>
   *
   * <code>uint32 satelliteCount = 17;</code>
   */
  int getSatelliteCount();

  /**
   * <pre>
   *任务编号
   * </pre>
   *
   * <code>uint64 taskId = 18;</code>
   */
  long getTaskId();

  /**
   * <pre>
   *rtk经度
   * </pre>
   *
   * <code>double rtkLng = 19;</code>
   */
  double getRtkLng();

  /**
   * <pre>
   *rtk纬度
   * </pre>
   *
   * <code>double rtkLat = 20;</code>
   */
  double getRtkLat();

  /**
   * <pre>
   *rtk海拔高度(平均海平面高度)(单位:米)
   * </pre>
   *
   * <code>float rtkHFSL = 21;</code>
   */
  float getRtkHFSL();

  /**
   * <pre>
   *rtk状态(值为50时[rtk数据fix固定解]，rtk的经纬度及海拔高度值可用)
   * </pre>
   *
   * <code>uint32 rtkPositionInfo = 22;</code>
   */
  int getRtkPositionInfo();

  /**
   * <pre>
   *当前架次飞行时长(单位:秒)
   * </pre>
   *
   * <code>uint32 airFlyTimes = 23;</code>
   */
  int getAirFlyTimes();

  /**
   * <pre>
   *当前架次飞行实际距离(单位:米)
   * </pre>
   *
   * <code>float airFlyDistance = 24;</code>
   */
  float getAirFlyDistance();

  /**
   * <pre>
   *无人机编号
   * </pre>
   *
   * <code>string uavSn = 25;</code>
   */
  String getUavSn();
  /**
   * <pre>
   *无人机编号
   * </pre>
   *
   * <code>string uavSn = 25;</code>
   */
  com.google.protobuf.ByteString
      getUavSnBytes();

  /**
   * <pre>
   *无人机型号
   * </pre>
   *
   * <code>string uavModel = 26;</code>
   */
  String getUavModel();
  /**
   * <pre>
   *无人机型号
   * </pre>
   *
   * <code>string uavModel = 26;</code>
   */
  com.google.protobuf.ByteString
      getUavModelBytes();

  /**
   * <pre>
   *距降落点距离(单位:米)
   * </pre>
   *
   * <code>float homeRange = 27;</code>
   */
  float getHomeRange();

  /**
   * <pre>
   *飞行模式：1=手动控制模式，2=姿态模式，6=MODE_P_GPS，9=热点任务中，11=自动起飞中，12=降落中，14=航线中，15=返航中，17=虚拟摇杆控制中，33=强制降落中，41=解锁电机准备起飞中
   * </pre>
   *
   * <code>uint32 flightMode = 28;</code>
   */
  int getFlightMode();
}
